---
title: "Homework Four"
output: html_document
---

# Homework Four: Due Sept. 23  at 5 pm.

First, download your homework. In your RStudio, fill in the below command:

```{r, eval = FASLE}
download.file(url = "https://raw.githubusercontent.com/BiologicalDataAnalysis2019/2022/main/vignettes/homework_4.Rmd", destfile = "/cloud/project/homeworks/homework_4.Rmd")

```

# Question One:

Take a look at [this](https://github.com/ropensci/treedata.table) package. Reading the documentation, what is the primary goal of this package? 


```
This package is about understanding the data.table package and its wrapper treedata.table to analzye phylogenetic trees.
```

# Question Two

Where in this package is the actual code stored? How do you know?

```
It is stored on github but sourced through ropensci. This is known because that is the domain listed.

```

# Question 3

When you look into the code, are you able to understand any of it? What is one thing the authors could do to make the code more understandable?

```
From my pointview this code makes sense and there isn't too much editing I would do. 
```

# Question 4

What are the other directories in the package? What do they contain?

```
This package contains the ropensci and treedata.table directories. ropensci is a  rOpenSci is a scientific open source project whose primary mission is to promote development and use of high-quality research software in the research community. treedata.table is a package that tries to be more efficient at analyzing phyogentic tree data. 

```

# Question 5

Do you trust that this package does what it says it is doing? Why or why not? 

```
Yes I do becuase I have installed this package, and then utillized the two examples from the section what can you do with "treedata.table". This worked for me. 
```

# Question 6

Have a look at [these](https://libguides.bc.edu/dataplan/best_practices) data storage best practices from Boston College. Have this read by Sept. 27 as we will use this in an activity.

## Master's Students

Find a package that does something you'd like to do for your dissertation. Apply the steps above to this package to evaluate its reliability.
